language: r
os: linux
cache: packages

script:
- R CMD build . --no-build-vignettes
- travis_wait 20 R CMD check *tar.gz --ignore-vignettes

jobs:
  include:
  - r: oldrel
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    after_failure: cat osfr.log
