language: r
os: linux
cache: packages

script:
- R CMD build . --no-build-vignettes
- travis_wait 20 R CMD check *tar.gz --ignore-vignettes

jobs:
  include:
  - r: oldrel
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    after_failure:
    - cat osfr.log
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      on:
        branch: master
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
