language: r
os: linux
cache: packages

install:
- R -e 'install.packages("remotes")'
- R -e 'remotes::install_deps(dep = T)'

script:
- R CMD build . --no-build-vignettes
- travis_wait 20 R CMD check *tar.gz --ignore-vignettes

jobs:
  include:
  - r: oldrel
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    after_failure:
    - cat osfr.log
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      on:
        branch: fix-pkgdown
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      cleanup: false
